(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'zenburn t)
(setq vc-follow-symlinks t)
(setq-default indent-tabs-mode nil)
(setq auto-save-default nil)
(setq make-backup-files nil)
(setq create-lockfiles nil)
