# If you come from bash you might have to change your $PATH.
#export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7

ZSH_CUSTOM=$HOME/custom-zsh-config
ZSH_THEME="kiuk"

COMPLETION_WAITING_DOTS="true"

plugins=(
    autojump
    git-prompt
    zsh-syntax-highlighting
    zsh-autosuggestions
    shrink-path
    amazon
)

export PATH=$PATH:$HOME/bin:/usr/local/cuda/bin
#export LD_LIBRARY_PATH=/usr/local/cuda/lib:$LD_LIBRARY_PATH

source $ZSH/oh-my-zsh.sh

