# If you come from bash you might have to change your $PATH.
#export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7

ZSH_CUSTOM=$HOME/custom-zsh-config
ZSH_THEME="kiuk"

COMPLETION_WAITING_DOTS="true"

ZSH_PYENV_QUIET="true"

plugins=(
    pyenv
    autojump
    git-prompt
    zsh-syntax-highlighting
    zsh-autosuggestions
    shrink-path
    google
)

export PATH=$PATH:$HOME/bin:/usr/local/cuda/bin
#export LD_LIBRARY_PATH=/usr/local/cuda/lib:$LD_LIBRARY_PATH

source $ZSH/oh-my-zsh.sh


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/conda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/conda/etc/profile.d/conda.sh" ]; then
        . "/opt/conda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

